version: '3'

services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/client

  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SECRET_KEY=secretsecret
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI=http://localhost/oauth2callback
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=secret
    volumes:
      - media:/media
      - ./server:/server
    depends_on:
      - database

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - media:/data/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - client
    - server

  database:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - 3306:3306

volumes:
  media:
